version: "3.8"

services:
  db:
    container_name: db
    image: mysql:8.0.42
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  cache:
    container_name: cache
    image: redis:8.0.2-alpine3.21
    ports:
      - 6379:6379