### sign up
POST localhost:3000/api/v1/members
Content-Type: application/json

{
  "name": "ddagae0805",
  "email": "ddagae0805@gmail.com",
  "password": "ddagae0805",
  "phone": "01011111111",
  "role": "ADMIN"
}

### login
POST localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "ddagae0805@gmail.com",
  "password": "ddagae0805"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### members list
GET localhost:3000/api/v1/members
Content-Type: application/json
Authorization: Bearer {{accessToken}}