### login
POST localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "ddagae0805@gmail.com",
  "password": "ddagae0805"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### POST /api/v1/orders
POST localhost:3000/api/v1/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "data": [
    {
      "itemId": 1,
      "quantity": 1
    }
  ]
}